import Head from 'next/head'
import Link from 'next/link';
import styles from '../styles/Home.module.css'

export default function Home({author}) {
    return ( <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>
          <h1 className={styles.title}>
            Sobre o Sistema
          </h1>

          O Sistema foi feito em live para demosntrar os primeiros passos com o Next.JS

            <hr/>
            Autor: {author}
          
          
  

        </main>
    
      </div>)
    } 

    export async function getServerSideProps() {
     return {
        props : {
          author: 'João Victor'

        }
      };
      
    }